title: Goon Hacker
description: "security is myth"
author:
  name: "Goon Hacker"
  email: "goonhacker0@gmail.com"
  url: "https://goonhacker.ga"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: category

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Goon"
year : "2021"
